-- MySQL Script generated by MySQL Workbench
-- Fri Jun 22 11:47:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`Mitglieder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Mitglieder` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Mitglieder` (
  `MitgliedID` INT NOT NULL AUTO_INCREMENT,
  `Vorname` VARCHAR(45) NULL,
  `Nachname` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `PWHash` VARCHAR(45) NULL,
  `Straße` VARCHAR(45) NULL,
  `PLZ` VARCHAR(45) NULL,
  `Ort` VARCHAR(45) NULL,
  PRIMARY KEY (`MitgliedID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Zeiten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Zeiten` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Zeiten` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gekommen` DATETIME NULL,
  `gegangen` DATETIME NULL,
  `MitgliedID` INT NOT NULL,
  PRIMARY KEY (`id`, `MitgliedID`),
  INDEX `fk_Zeiten_Mitglieder_idx` (`MitgliedID` ASC),
  CONSTRAINT `fk_Zeiten_Mitglieder`
    FOREIGN KEY (`MitgliedID`)
    REFERENCES `hotel`.`Mitglieder` (`MitgliedID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
